検証対象コードの説明の追加
FEABeRjp/FEABeR pull request #36
Opened 2022-05-29 09:39 UTC by mmer547

現在、トップページしかインデックスが作られていなさそうなので、トップページにソフトウェア名称が出るようにして検索に引っかかるようにしようと思っています。

2022-05-29 09:41 UTC, mmer547 commented
インストール方法はシンポジウムまでに追加しようと思います。

2022-06-04 10:27 UTC, tkoyama010 requested changes
レビュー遅くなりました。追加ありがとうございます。

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/getfem.rst
> +本プロジェクトで使用するソフトウェアの一覧を示します。各ソフトウェアについてはそれぞれのページをご覧ください。
```suggestion
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/getfem.rst
> +日本語のページは `こちら <https://getfem.readthedocs.io/ja/latest/contents.html#>`_ です。
```suggestion
日本語のページは `こちら <https://getfem.readthedocs.io/ja/latest/index.html>`_ です。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/codeaster.rst
> +Code-Asterは次のサイトで公開されています。
```suggestion
以下のサイトで公開されています。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/frontistr.rst
> +FrontISTRはこちらのサイトで公開されています。
```suggestion
以下のサイトで公開されています。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/getfem.rst
> +GetFEMは次のサイトで公開されています。
```suggestion
GetFEMは以下のサイトで公開されています。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/codeaster.rst
> +https://www.code-aster.org/spip.php?rubrique2
リンクにアクセスできなかったので修正しました。
```suggestion
https://www.code-aster.org/
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/calculix.rst
> +CalculiXについては次のサイトで公開されています。
表記に揺れがあったので「以下」で統一しました。
```suggestion
以下のサイトで公開されています。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/calculix.rst
> +CalculiXは有限要素法を使用したオープンソースの解析コードです。CalculiXは有限要素モデルの構築、計算、ポスト処理ができます。CalculiXはGUIであるcgxとソルバであるccxが提供されています。
```suggestion
CalculiXは有限要素法を使用したオープンソースの解析コードです。有限要素モデルの構築、計算、ポスト処理を行うことができます。GUIのcgxとソルバのccxが提供されています。
```

2022-06-04 10:27 UTC, tkoyama010 commented on doc/solver/codeaster.rst
> +プリポストを統合したSalome-Mecaも公開されており、商用CAEソフトウェアと同様の操作で計算できます。
```suggestion
プリポストを統合したSalome-Mecaが公開されており、商用CAEソフトウェアと同様の操作で計算できます。
```

2022-07-31 05:56 UTC, mmer547 reviewed
レビューいただいた内容を反映しました。

2022-07-31 07:54 UTC, tkoyama010 approved these changes
LGTM

2022-07-31 07:55 UTC, merged